version: 2.1
jobs:
  sample:
    working_directory: ~/code 
    docker: 
      - image: circleci/node:12.16
    steps:
      - checkout
      - run: 
          name: Test
          command: echo 'helo there!' 
  other:
    working_directory: ~/code
    docker:
      - image: circleci/node:12.16 
    steps: 
      - checkout 
      - run: 
          name: Date
          command: date
workflows:
  version: 2
  sample-run:
    jobs:
      - sample:
          filters:
            branches:
              ignore:
                - develop
  other-run:
    jobs:
      - sample:
          filters:
            branches:
              ignore:
                - develop
      - other
